### ISSUE TITLE
Lone asterisk (*) and slash (/) are treated as normal parameters

### ISSUE THREAD

**Issue by ErikBachmann42** [JanEricNitschke/pyment#7]
A lone asterisk (*) can be used to mark that all following arguments must be passed as keyword arguments. Similarly, a lone slash (/) signifies that all previous arguments must be passed positionally. Currently, they are treated as normal parameters. For example, for
```
def foo(x: int, y: int, *, a: int, b: int) -> None:
    pass
```
the following docstring is generated:
```
"""_summary_.

Parameters
----------
x : int
    _description_
y : int
    _description_
* : _type_
    _description_
a : int
    _description_
b : int
    _description_

Returns
-------
None
    _description_
"""
```

**Comment by JanEricNitschke** [comment]
Should be fixed for tag "v0.3.31" in https://github.com/JanEricNitschke/pyment/commit/5f4f6e5cd6299b6aa9cf83f1842ea783a0e3afb4
